"""recreate full schema

Revision ID: 1d1bcd4fad17
Revises: 
Create Date: 2025-10-25 18:54:46.028420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1bcd4fad17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_embedding', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('voice_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('security_question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('security_answer_hash')
        batch_op.drop_column('security_question')
        batch_op.drop_column('voice_locked')
        batch_op.drop_column('voice_embedding')

    # ### end Alembic commands ###
